### ISSUE TITLE
Build: getting build error - "file could not load, no such file or directory"

### ISSUE THREAD

**Issue by baxy5** [layerhub-io/react-design-editor#1]
I was trying to contribute to your projects which I found a really great idea.
I forked and cloned the repo, I was started to make that small change, but when I tried to build this error popped up.
![image](https://user-images.githubusercontent.com/58151931/180423506-9e5c891e-bef8-49ac-afeb-3f0475350ca9.png)
I could solve the problem when changing  ~  to  ../  but then I found out it will be a lot of time to change everything in this huge code base.
I don't know that it's a bug or just I am a noob but I wrote this issue just in case.
(I've never used this ~ )

**Comment by chloe-bm** [comment]
@baxy5 Pretty weird, could not reproduce it.

Steps followed:
1. git clone
2. pnpm i
3. pnpm build
 
Node version: v18.3.0
pnpm version: 7.2.1

**Comment by baxy5** [comment]
Node version: ✅
pnpm version: ✅
Still getting that interesting error. :(

**Comment by baxy5** [comment]
~ <-- what's this?

**Comment by xorb** [comment]
It is used for absolute path imports. Instead of `../../../../components`, you can do: `~/src/components`

**Comment by baxy5** [comment]
And why is that not working for me? because when I replace with `../../` there is no error. Of course it is not solve the problem because there are more than 300 import which uses `~`.

**Comment by xorb** [comment]
Not sure about that. Probably windows specific issue. Cannot reproduce it on linux based distros.

**Comment by chloe-bm** [comment]
Probably it is a windows specific issue. Could not reproduce on linux based distros.

**Comment by rushmedev** [comment]
Facing a similar kind of issue. Maybe some OS-specific issue.

**Comment by chloe-bm** [comment]
It may be. Maybe you can try with WSL2.

**Comment by chloe-bm** [comment]
I will try it on Windows and see what we can do for you guys.

**Comment by rushmedev** [comment]
I will install Linux on my system I need this project and kinda need Docker support also.

**Comment by chloe-bm** [comment]
You can always join our discord server and ask anything.

**Comment by chloe-bm** [comment]
It should work on windows now.

**Comment by rushmedev** [comment]
Thanks that's fast.
