### ISSUE TITLE
How can we download as PNG without background?

### ISSUE THREAD

**Issue by AkilLis** [layerhub-io/react-design-editor#45]
Hello

Trying to Export PNG with transparent background but it downloaded Frame with white backgroundColor. How can we remove the background?

The purpose of using png is a customized picture-generating clothes mockup.

**Comment by chloe-bm** [comment]
There is a render menthod in the SDK, it returns a base64 image. You can either display it or download it. Or both.

The render menthod accepts an array of layers. First layer should be background, you can remove before using render method.

https://github.com/layerhub-io/react-design-editor/blob/93f709630604a2a11857507bd59228d2d0bdb715/src/views/DesignEditor/components/Preview/Graphic.tsx#L15

**Comment by chloe-bm** [comment]
Try this demo: https://github.com/layerhub-pro/react-design-editor

**Comment by AkilLis** [comment]
@chloe-bm. Okay nice. Let me try this. As mentioned repo how we change t-shirt any other clothes placeholder as a parameter currently it is fixed in @layerhub-io/react library right?

**Comment by AkilLis** [comment]
> There is a render menthod in the SDK, it returns a base64 image. You can either display it or download it. Or both.
> 
> The render menthod accepts an array of layers. First layer should be background, you can remove before using render method.
> 
> https://github.com/layerhub-io/react-design-editor/blob/93f709630604a2a11857507bd59228d2d0bdb715/src/views/DesignEditor/components/Preview/Graphic.tsx#L15

Works as expected
